name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for creating your first issue! We appreciate your contribution to our project. Our team will review it soon."
        pr-message: "Congratulations on your first pull request! We are thrilled to see your contribution. Our team will review your PR soon."
